repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: end-of-file-fixer
        types: [python]
      - id: check-yaml
      - id: check-added-large-files
